### ISSUE TITLE
Block Break Restrictions

### ISSUE THREAD

**Issue by MultiDragon** [Gerold55/WasteLands_Survival#41]
Currently, plank breaking (and maybe a couple other things) use `minetest.register_on_dignode` function [here](https://github.com/Gerold55/WasteLands_Survival/blob/master/mods/ws_core/nodes.lua#L3). It's fundamentally wrong due to several reasons:
* It doesn't follow other mods' conventions. Usually MT mods just disallow breaking nodes with hand if they don't want it to be breakable (i.e., adding `cracky` itemgroup. We can remove `choppy` itemgroup from hand tool definition to achieve the same effect).
* It's counterintuitive. If you don't want a block to be breakable just change hand tool definition.
* (not `register_on_dignode` issue, but related to planks) hand is breaking wood faster than axe, which is strange.
* It can often break other mods. I don't think mods often have `axe` or `hatchet` itemgroup on their tools.
* It breaks creative. If you break a wood block in creative, it appears back, which is a no-go. Even worse, if you had plank block in inventory you lose it!
* Speaking of creative: creative hand isn't overridden. It can't break stone and breaks other nodes very slowly.

I propose the following changes:
* Override creative hand so it can break anything with a good speed.
* Remove `register_on_dignode` triggers. (using it in something like `journal` to trigger researches is fine)
* Change survival hand by removing `choppy` group from its tool definition.
* If you really want damage, you can also add `on_punch` function to its definition. (not sure how it's named though)

**Comment by Gerold55** [comment]
What would you suggest to fix the issue?

**Comment by theFox6** [comment]
Look at the last section

**Comment by theFox6** [comment]
Look at the last section

**Comment by Skamiz** [comment]
This can be closed I believe.
With the merging of #57 the confusing damage mechanic was removed. #56 made wooden nodes unbreakable by hand and #53 fixed the issue with the creative hand.
