### ISSUE TITLE
Fix Buckets

### ISSUE THREAD

**Issue by Gerold55** [Gerold55/WasteLands_Survival#47]
**Describe the bug**
When placing water from a bucket it changes to the wrong bucket.

**To Reproduce**
Place a clay bucket of water.

**Expected behavior**
Place water from clay bucket and give an empty clay bucket back.

**Desktop (please complete the following information):**
 - Minetest version: 5.2.0

**Comment by theFox6** [comment]
There is more trouble with the buckets. The bucket mod is very messy and there are more buckets that turn into the wrong ones.

**Comment by Skamiz** [comment]
Will look into this. Another thing, there is no oil holding variant of the clay bucket, should I add it?

**Comment by Gerold55** [comment]
We were thinking that clay buckets can't hold oil... so you need an iron bucket

**Comment by Skamiz** [comment]
Why wouldn't clay buckets be able to hold oil?

**Comment by Gerold55** [comment]
I was thinking that clay buckets would only durable enough for water...

**Comment by Skamiz** [comment]
And how is oil more dammaging to the bucket then water?

**Comment by Gerold55** [comment]
🤷‍♂️ It's something I came up with...
